### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidhealey** [craigfrancis/hmrc-rti#1]
What license is this software released under? I couldn't see a license file or license header in the source code.

**Comment by craigfrancis** [comment]
Good point, it’s under the BSD licence:

https://www.craigfrancis.co.uk/terms/codeLicence/

I’ll look at adding it to the repository tomorrow.

**Comment by craigfrancis** [comment]
Thanks @davidhealey, I've added a Licence file to the project:

https://github.com/craigfrancis/hmrc-rti/blob/main/LICENSE.md
